### ISSUE TITLE
npm test fails with io.js

### ISSUE THREAD

**Issue by trlim** [quartzjer/telehash-udp4#1]
The first error seems to be the same with [this](https://github.com/iojs/io.js/issues/554).
No idea on the second one.
Running io.js 1.3.0 on Windows 8.

```
$ npm test

> telehash-udp4@0.0.12 test E:\workspace\telehash\telehash-js\node_modules\telehash-udp4
> make test

./node_modules/.bin/mocha --reporter list

  . udp4 exports an object: 2ms
  . udp4 is an extension: 0ms
  . udp4 extends a mock mesh: 0ms
  . udp4 returns paths array: 16ms
  . udp4 returns a public path: 0ms
  1) udp4 enables discovery
  . udp4 skips unknown pipe: 0ms
  . udp4 creates a pipe: 0ms
  2) udp4 sends a packet
  . udp4 handles empty packet: 0ms

  8 passing (27ms)
  2 failing

  1) udp4 enables discovery:
     Uncaught Error: bind EADDRINUSE 0.0.0.0:61167
      at Object.exports._errnoException (util.js:734:11)
      at exports._exceptionWithHostPort (util.js:757:20)
      at dgram.js:206:18
      at dns.js:66:18
      at process._tickCallback (node.js:337:11)

  2) udp4 sends a packet:
     Error: done() invoked with non-Error: 0
      at SendWrap.callback (E:\workspace\telehash\telehash-js\node_modules\telehash-udp4\node_modules\mocha\lib\runnable.js:224:25)
      at SendWrap.afterSend [as oncomplete] (dgram.js:339:8)
```

**Comment by quartzjer** [comment]
Thanks! I've not gotten to a thorough testing of v0.12, iojs, or window yet for all the telehash-js packages, this is getting me started at least :)
